---
name: Build and Test
on:
  push:
    branches: [dev2]
  pull_request:
    branches: [dev2]
#  schedule:
#    - cron:  '0 0 * * 0' # weekly
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
#        os: [ubuntu-latest, macos-latest,windows-latest]
        os: [ubuntu-latest]
        shared_libs: ['OFF']
        include:
          - os: ubuntu-latest
            triplet: 'x64-linux'
            prefix_path=$HOME/install
            tmp_path=$HOME/tmp
          - os: macos-latest
            triplet: 'x64-osx'
            prefix_path=$HOME/install
            tmp_path=$HOME/tmp
          - os: windows-latest
            triplet: 'x64-windows'
            prefix_path=%cd:\=/%/install
            tmp_path=%cd:\=/%/tmp
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: echo hello
        run: |
          echo "Hello world!"
          
      - name: build nlopt
        run: |
          echo "Build NLopt"
          mkdir ${{ tmp_path }}
          mkdir ${{ prefix_path }}
          cd    ${{ prefix_path }}
          # git clone git@github.com:stevengj/nlopt.git
          # cd nlopt
          # mkdir build
          # cd    build
          # echo "pwd=`pwd`"          

#jobs:
#  build:
#    runs-on: ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [ubuntu-latest]
#        build_type: [Release]
#        include:
#          - os: ubuntu-latest
#            triplet: 'x86-linux'
#            cmake_flags: '${{ nlopt_flags }} -DCMAKE_PREFIX_PATH=${{ inst_path }} -DCMAKE_INSTALL_PREFIX=${{ inst_path }}'
#    steps:
#      - name: "Install NLopt"
#        run: |
#          mkdir -p ${{github.workspace}}/install
#          mkdir -p tmp/nlopt/build
#          cd tmp 
#          git clone git@github.com:stevengj/nlopt.git
#          cd nlopt/build
#          cmake -DBUILD_SHARED_LIBS=OFF -DNLOPT_CXX=ON -DNLOPT_PYTHON=OFF -DNLOPT_GUILE=OFF -DNLOPT_SWIG=OFF -DNLOPT_OCTAVE=OFF -DNLOPT_MATLAB=OFF -DNLOPT_TESTS=OFF -Wno-dev -DCMAKE_PREFIX_PATH=${{github.workspace}}/install -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -H.. && cmake --build . -j 4 --target install
