---
name: Build and Test
on:
  push:
    branches: [dev2]
  pull_request:
    branches: [dev2]
#  schedule:
#    - cron:  '0 0 * * 0' # weekly
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
#        os: [ubuntu-latest, macos-latest,windows-latest]
        os: [ubuntu-latest]
        shared_libs: ['OFF']
        include:
          - os: ubuntu-latest
            triplet: 'x64-linux'
            CMAKE_TOOLCHAIN_FILE: '${{ github.workspace }}/VcPkg/vcpkg/scripts/buildsystems/vcpkg.cmake'
            CMAKE_BUILD_TYPE: Release
          - os: macos-latest
            triplet: 'x64-osx'
            CMAKE_TOOLCHAIN_FILE: '${{ github.workspace }}/VcPkg/vcpkg/scripts/buildsystems/vcpkg.cmake'
            CMAKE_BUILD_TYPE: Release
          - os: windows-latest
            triplet: 'x64-windows'
            CMAKE_TOOLCHAIN_FILE: '${{ github.workspace }}\VcPkg\vcpkg\scripts\buildsystems\vcpkg.cmake'
            CMAKE_BUILD_TYPE: Release
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: echo hello
        run: |
          echo "Hello world!"
          
      - name: "build NLopt"
        run: |
          echo "Build NLopt"
          echo "# 1a.) Configuring VCPKG ..."
          vcpkg install

      - name: "prepare NLoptWr"
        if: ${{ contains(matrix.os, 'macos') }}
        run: |
          echo "Configure NLoptWr for macos"
          brew install llvm libomp
          sudo ln -s /usr/local/opt/llvm/bin/clang    /usr/local/bin/clang-omp
          sudo ln -s /usr/local/opt/llvm/bin/clang++  /usr/local/bin/clang-omp++
          export CC=/usr/local/bin/clang-omp
          export CXX=/usr/local/bin/clang-omp++
          export CPPFLAGS="-I/usr/local/opt/llvm/include"
          export CXXFLAGS="-I/usr/local/opt/llvm/include"
          export LDFLAGS="-L/usr/local/opt/llvm/lib"
          export OpenMP_C=${CC}
          export OpenMP_CXX=${CXX}
          export OpenMP_C_FLAGS="-fopenmp=libomp -Wno-unused-command-line-argument"
          export OpenMP_C_LIB_NAMES="libomp libgomp libiomp5"
          export CMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake
          export VCPKG_DEFAULT_TRIPLET=x64-osx
          export VCPKG_TRIPLET=x64-osx

#jobs:
#  build:
#    runs-on: ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [ubuntu-latest]
#        build_type: [Release]
#        include:
#          - os: ubuntu-latest
#            triplet: 'x86-linux'
#            cmake_flags: '${{ nlopt_flags }} -DCMAKE_PREFIX_PATH=${{ inst_path }} -DCMAKE_INSTALL_PREFIX=${{ inst_path }}'
#    steps:
#      - name: "Install NLopt"
#        run: |
#          mkdir -p ${{github.workspace}}/install
#          mkdir -p tmp/nlopt/build
#          cd tmp 
#          git clone git@github.com:stevengj/nlopt.git
#          cd nlopt/build
#          cmake -DBUILD_SHARED_LIBS=OFF -DNLOPT_CXX=ON -DNLOPT_PYTHON=OFF -DNLOPT_GUILE=OFF -DNLOPT_SWIG=OFF -DNLOPT_OCTAVE=OFF -DNLOPT_MATLAB=OFF -DNLOPT_TESTS=OFF -Wno-dev -DCMAKE_PREFIX_PATH=${{github.workspace}}/install -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -H.. && cmake --build . -j 4 --target install
