---
name: Build and Test
on:
  push:
    branches: [dev2]
  pull_request:
    branches: [dev2]
#  schedule:
#    - cron:  '0 0 * * 0' # weekly
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
#        os: [ubuntu-latest, macos-latest,windows-latest]
        os: [ubuntu-latest]
        shared_libs: ['OFF']
        include:
          - os: ubuntu-latest
            triplet: 'x64-linux'
            CMAKE_TOOLCHAIN_FILE: '${{ github.workspace }}/VcPkg/vcpkg/scripts/buildsystems/vcpkg.cmake'
          - os: macos-latest
            triplet: 'x64-osx'
            CMAKE_TOOLCHAIN_FILE: '${{ github.workspace }}/VcPkg/vcpkg/scripts/buildsystems/vcpkg.cmake'
          - os: windows-latest
            triplet: 'x64-windows'
            CMAKE_TOOLCHAIN_FILE: '${{ github.workspace }}\VcPkg\vcpkg\scripts\buildsystems\vcpkg.cmake'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: echo hello
        run: |
          echo "Hello world!"
          
      - name: "build nlopt (*nix)"
        if: ${{ !contains(matrix.os, 'windows') }}
        run: |
          echo "Build NLopt for Non-Windows"
          echo "# 1a.) Configuring VCPKG ..."
          mkdir -p ${{github.workspace}}/VcPkg
          cd       ${{github.workspace}}/VcPkg
          git clone https://github.com/microsoft/vcpkg
          echo "# 1b.) VCPKG: clone done"
          cd ${{github.workspace}}/VcPkg/vcpkg
          bootstrap-vcpkg.sh -disableMetrics
          set VCPKG_DEFAULT_TRIPLET=${{ triplet }}
          set VCPKG_TRIPLET=${{ triplet }}
          vcpkg install
          echo "# 1c.) VCPKG installed"
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          echo "# 1d.) build directory created"
          set CMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\VcPkg\vcpkg\scripts\buildsystems\vcpkg.cmake
          echo "CMAKE_TOOLCHAIN_FILE: ${{ CMAKE_TOOLCHAIN_FILE }}"

      - name: "build nlopt (win)"
        if: ${{ contains(matrix.os, 'windows') }}
        shell: cmd
        run: |
          echo "Build NLopt for Windows"
          echo "# 1a.) Configuring VCPKG ..."
          mkdir -p ${{github.workspace}}\VcPkg
          cd       ${{github.workspace}}\VcPkg
          git clone https://github.com/microsoft/vcpkg
          echo "# 1b.) VCPKG: clone done"
          cd ${{github.workspace}}\VcPkg\vcpkg
          bootstrap-vcpkg.sh -disableMetrics
          set VCPKG_DEFAULT_TRIPLET=${{ triplet }}
          set VCPKG_TRIPLET=${{ triplet }}
          vcpkg install
          echo "# 1c.) VCPKG installed"
          mkdir ${{github.workspace}}\build
          cd ${{github.workspace}}\build
          echo "# 1d.) build directory created"
          set CMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\VcPkg\vcpkg\scripts\buildsystems\vcpkg.cmake
          echo "CMAKE_TOOLCHAIN_FILE: ${{ CMAKE_TOOLCHAIN_FILE }}"

#jobs:
#  build:
#    runs-on: ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [ubuntu-latest]
#        build_type: [Release]
#        include:
#          - os: ubuntu-latest
#            triplet: 'x86-linux'
#            cmake_flags: '${{ nlopt_flags }} -DCMAKE_PREFIX_PATH=${{ inst_path }} -DCMAKE_INSTALL_PREFIX=${{ inst_path }}'
#    steps:
#      - name: "Install NLopt"
#        run: |
#          mkdir -p ${{github.workspace}}/install
#          mkdir -p tmp/nlopt/build
#          cd tmp 
#          git clone git@github.com:stevengj/nlopt.git
#          cd nlopt/build
#          cmake -DBUILD_SHARED_LIBS=OFF -DNLOPT_CXX=ON -DNLOPT_PYTHON=OFF -DNLOPT_GUILE=OFF -DNLOPT_SWIG=OFF -DNLOPT_OCTAVE=OFF -DNLOPT_MATLAB=OFF -DNLOPT_TESTS=OFF -Wno-dev -DCMAKE_PREFIX_PATH=${{github.workspace}}/install -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -H.. && cmake --build . -j 4 --target install
