---
name: Build and Test
on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
#        os: [ubuntu-latest, ubuntu-20.04, windows-latest, macos-latest, macos-10.15]
        os: [ubuntu-latest]
        shared_libs: ['OFF']
        include:
          - os: ubuntu-latest
            triplet: 'x64-linux'
            cmake_flags: '-DCMAKE_CXX_COMPILER=clang++'
          - os: ubuntu-latest
            triplet: 'x64-linux'
            cmake_flags: '-DCMAKE_CXX_COMPILER=clang++'
          - os: ubuntu-20.04
            triplet: 'x64-linux'
            cmake_flags: '-DCMAKE_CXX_COMPILER=g++'
          - os: windows-latest
            triplet: 'x64-windows'
            cmake_flags: '""'
          - os: macos-latest
            triplet: 'x64-osx'
            cmake_flags: ''
          - os: macos-10.15
            triplet: 'x64-osx'
            cmake_flags: ''
        exclude:
          # tests won't build with shared libs due to private symbols
          - shared_libs: 'ON'
            tests: 'ON'
          - shared_libs: 'OFF'
            tests: 'OFF'
          # Disabled until https://github.com/sgieseking/anyrpc/pull/43 is in place
          - os: windows-latest
            shared_libs: 'ON'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

#jobs:
#  build:
#    runs-on: ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [ubuntu-latest]
#        build_type: [Release]
#        include:
#          - os: ubuntu-latest
#            triplet: 'x86-linux'
#            cmake_flags: '${{ nlopt_flags }} -DCMAKE_PREFIX_PATH=${{ inst_path }} -DCMAKE_INSTALL_PREFIX=${{ inst_path }}'
#    steps:
#      - name: "Install NLopt"
#        run: |
#          mkdir -p ${{github.workspace}}/install
#          mkdir -p tmp/nlopt/build
#          cd tmp 
#          git clone git@github.com:stevengj/nlopt.git
#          cd nlopt/build
#          cmake -DBUILD_SHARED_LIBS=OFF -DNLOPT_CXX=ON -DNLOPT_PYTHON=OFF -DNLOPT_GUILE=OFF -DNLOPT_SWIG=OFF -DNLOPT_OCTAVE=OFF -DNLOPT_MATLAB=OFF -DNLOPT_TESTS=OFF -Wno-dev -DCMAKE_PREFIX_PATH=${{github.workspace}}/install -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -H.. && cmake --build . -j 4 --target install
