---
name: Mac
# on: [push, pull_request]
on: [pull_request]

jobs:

  mac:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install OpenMP and set environment variables
        run: |
          brew install llvm libomp
          sudo ln -s /usr/local/opt/llvm/bin/clang    /usr/local/bin/clang-omp
          sudo ln -s /usr/local/opt/llvm/bin/clang++  /usr/local/bin/clang-omp++
          export CC=/usr/local/bin/clang-omp
          export CXX=/usr/local/bin/clang-omp++
          export CPPFLAGS="-I/usr/local/opt/llvm/include"
          export CXXFLAGS="-I/usr/local/opt/llvm/include"
          export LDFLAGS="-L/usr/local/opt/llvm/lib"
          export OpenMP_C=${CC}
          export OpenMP_CXX=${CXX}
          export OpenMP_C_FLAGS="-fopenmp=libomp -Wno-unused-command-line-argument"
          export OpenMP_C_LIB_NAMES="libomp libgomp libiomp5"
          export CMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake
          export VCPKG_DEFAULT_TRIPLET=x64-osx
          export VCPKG_TRIPLET=x64-osx

      - name: Install NLOpt
        run: |
          echo "Set environment variables "
          export CC=/usr/local/bin/clang-omp
          export CXX=/usr/local/bin/clang-omp++
          export LDFLAGS="-L/usr/local/opt/llvm/lib"
          export CPPFLAGS="-I/usr/local/opt/llvm/include"
          export CXXFLAGS="-I/usr/local/opt/llvm/include"
          export OpenMP_C=${CC}
          export OpenMP_CXX=${CXX}
          export OpenMP_C_FLAGS="-fopenmp=libomp -Wno-unused-command-line-argument"
          export OpenMP_C_LIB_NAMES="libomp libgomp libiomp5"
          export CMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake
          export VCPKG_DEFAULT_TRIPLET=x64-osx
          export VCPKG_TRIPLET=x64-osx
          echo "CMAKE_TOOLCHAIN_FILE:  ${CMAKE_TOOLCHAIN_FILE}"
          echo "VCPKG_DEFAULT_TRIPLET: ${VCPKG_DEFAULT_TRIPLET}"
          echo "VCPKG_TRIPLET:         ${VCPKG_TRIPLET}"
          echo " "
          echo "CPPFLAGS:              ${CPPFLAGS}"
          echo "CXXFLAGS:              ${CXXFLAGS}"
          echo "LDFLAGS:               ${LDFLAGS}"
          echo "CXX:                   ${LDFLAGS}"
          echo "OpenMP_C_FLAGS:        ${OpenMP_C_FLAGS} "
          echo "OpenMP_C_LIB_NAMES:    ${OpenMP_C_LIB_NAMES} "
          vcpkg install

      - name: Install NLOptWr and Test
        run: |
          echo "Check environment variables:"
          export CC=/usr/local/bin/clang-omp
          export CXX=/usr/local/bin/clang-omp++
          export LDFLAGS="-L/usr/local/opt/llvm/lib"
          export CPPFLAGS="-I/usr/local/opt/llvm/include"
          export CXXFLAGS="-I/usr/local/opt/llvm/include"
          export OpenMP_C=${CC}
          export OpenMP_CXX=${CXX}
          export OpenMP_C_FLAGS="-fopenmp=libomp -Wno-unused-command-line-argument"
          export OpenMP_C_LIB_NAMES="libomp libgomp libiomp5"
          export CMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake
          export VCPKG_DEFAULT_TRIPLET=x64-osx
          export VCPKG_TRIPLET=x64-osx
          echo "CMAKE_TOOLCHAIN_FILE:  ${CMAKE_TOOLCHAIN_FILE}"
          echo "VCPKG_DEFAULT_TRIPLET: ${VCPKG_DEFAULT_TRIPLET}"
          echo "VCPKG_TRIPLET:         ${VCPKG_TRIPLET}"
          echo " "
          echo "CPPFLAGS:              ${CPPFLAGS}"
          echo "CXXFLAGS:              ${CXXFLAGS}"
          echo "LDFLAGS:               ${LDFLAGS}"
          echo "CXX:                   ${LDFLAGS}"
          echo "OpenMP_C_FLAGS:        ${OpenMP_C_FLAGS} "
          echo "OpenMP_C_LIB_NAMES:    ${OpenMP_C_LIB_NAMES} "
          mkdir -p ${{github.workspace}}/build
          echo "Configure CMake completed?"
          echo "Configuration:"
          cd       ${{github.workspace}}/build
          #
          ### cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ..
          cmake  -DNLOPTWR_BUILD_EXAMPLES=OFF -DNLOPTWR_BUILD_TESTS=OFF -Wno-dev -DCMAKE_PREFIX_PATH=${{github.workspace}}/install -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}  -H${{github.workspace}} 
          echo "compilation:"
          cmake --build . -j 2 --target install 
          echo "test: "
          ctest
