name: Build
on: [push, pull_request]
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: cmd
        run: |
          echo "bootstrap done"
          mkdir -p ${{github.workspace}}\VcPkg
          cd       ${{github.workspace}}\VcPkg
          git clone https://github.com/microsoft/vcpkg
          echo "clone done"
          cd ${{github.workspace}}\VcPkg\vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg install --triplet x64-windows
          mkdir ${{github.workspace}}\build
          cd ${{github.workspace}}\build
          echo "YYY"
#          cmake -DCMAKE_TOOLCHAIN_FILE=${github.workspace}\VcPkg\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_INSTALL_PREFIX=%cd:\=/%/install ..
          echo "ZZZ"
          cmake --build . --config Release --target install
#
#        	vcpkg install nlopt
#          mkdir -p ${{github.workspace}}\VcPkg
#          cd       ${{github.workspace}}\VcPkg
#          git clone https://github.com/microsoft/vcpkg
#          echo "clone done"
#          cd ${{github.workspace}}\VcPkg\vcpkg
#          .\bootstrap-vcpkg.bat
#          vcpkg install --triplet x64-windows
#          vcpkg install nlopt
#          cmake -DCMAKE_TOOLCHAIN_FILE=${github.workspace}\VcPkg\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_INSTALL_PREFIX=%cd:\=/%/install ..
#
#          set VCPKG_ROOT=${{github.workspace}}\VcPkg\vcpkg
#          set CMAKE_TOOLCHAIN_FILE=${github.workspace}\VcPkg\vcpkg\scripts\buildsystems\vcpkg.cmake
#          ctest -C Release --output-on-failure --timeout 100
#          xcopy %cd%\install\bin\nlopt.dll %cd%\src\swig
#          xcopy %cd%\install\Lib\site-packages\_nlopt*.pyd %cd%\src\swig
#          dir /p %cd%\src\swig
#
#
#jobs:
#  windows:
#    build:
#    runs-on: windows-latest
#    steps:
#      - name: checkout
#        uses: actions/checkout@v3
#
#      - name: Build
#        shell: cmd
#        run: |
#          echo "vcpkg install nlopt"
#          echo "github.workspace: ${{github.workspace}} "
#          mkdir -p ${{github.workspace}}\VcPkg
#          cd       ${{github.workspace}}\VcPkg
#          git clone https://github.com/microsoft/vcpkg
#          echo "clone done"
#          cd       ${{github.workspace}}\VcPkg\vcpkg
#          echo "cd  ${{github.workspace}}\VcPkg\vcpkg done"
#          ${{github.workspace}}\VcPkg\vcpkg\bootstrap-vcpkg.bat
#          set VCPKG_ROOT=${{github.workspace}}\VcPkg\vcpkg
##          echo "bootstrap done"
#          vcpkg install --triplet x64-windows
##        mkdir D:\a\nloptwr\nloptwr\
##        mkdir ${{github.workspace}}\build
##        cd    ${{github.workspace}}\build
##        cd    D:\a\nloptwr\nloptwr\
##         pwd
##        echo "### "
###        cmake -DCMAKE_TOOLCHAIN_FILE="D:\a\nloptwr\nloptwr\VcPkg\vcpkg\scripts\buildsystems\vcpkg.cmake" -DCMAKE_INSTALL_PREFIX=c:/dev/projects/nloptwr/install .. 
##        cmake --build . --config Release --target install
##        ctest -C Release --output-on-failure --timeout 300  
##
##        set CMAKE_TOOLCHAIN_FILE="${github.workspace}\VcPkg\vcpkg\scripts\buildsystems\vcpkg.cmake"
##        set VCPKG_ROOT="${github.workspace}\VcPkg\vcpkg"
###        echo ${{VCPKG_ROOT}}
##        echo "CMAKE_TOOLCHAIN_FILE: $CMAKE_TOOLCHAIN_FILE"
##        mkdir -p ${{github.workspace}}/build
##        echo "BUILD_DIR=${github.workspace}/build"
##        set VCPKG_DEFAULT_TRIPLET=x64-windows
##        set VCPKG_TRIPLET=x64-windows
##        echo "pwd:"
##        echo "Configuration:"
##        cd  ${{github.workspace}}/build
##
##        cmake -DCMAKE_TOOLCHAIN_FILE="${{github.workspace}}/VcPkg/vcpkg/scripts/buildsystems/vcpkg.cmake" .. 
##  cmake -DCMAKE_TOOLCHAIN_FILE="D:\a\nloptwr\nloptwr\VcPkg\vcpkg\scripts\buildsystems\vcpkg.cmake" -S .. -B ${github.workspace}/build ..
#### -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
###        cmake -S . -B ${github.workspace}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

##
##    - name: Install nlopt
##      run: |
##        dir C:\vcpkg\scripts\buildsystems\vcpkg.cmake
##        setx CMAKE_TOOLCHAIN_FILE C:\vcpkg\scripts\buildsystems\vcpkg.cmake
##        # set CMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake
##        # set CMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
##        vcpkg install nlopt
#
#
##
##    - name: Configure CMake
##      run: |
##        echo "Configure CMake"
##        CMAKE_TOOLCHAIN_FILE=${{github.workspace}}/VcPkg/vcpkg/scripts/buildsystems/vcpkg.cmake cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
##        echo "Configure CMake completed?"
##    - name: Configure CMake
##      run: |
##        echo "Configure CMake"
##        mkdir -p ${{github.workspace}}/build
##        #
##        cmake -S . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
##        # setx CMAKE_TOOLCHAIN_FILE C:\vcpkg\scripts\buildsystems\vcpkg.cmake
##        # set CMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake
##        # set CMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake
##        echo  "Configure CMake completed?"
