name: Windows

on:
  label:
    types:
      - created
      - edited
  push:
    branches:
      - main
      - dev
      - dev-workflow
  pull_request:
    branches:
      - main
      - dev
      - dev-workflow

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo


jobs:

# ====================================================================
  build:
    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Install NLOPT
      run: |
        echo "vcpkg install nlopt"
        mkdir -p ${{github.workspace}}\VcPkg
        cd       ${{github.workspace}}\VcPkg
        git clone https://github.com/microsoft/vcpkg
        echo "clone done"
        cd       ${{github.workspace}}\VcPkg\vcpkg
        echo "cd  ${{github.workspace}}\VcPkg\vcpkg done"
        ${{github.workspace}}\VcPkg\vcpkg\bootstrap-vcpkg.bat
        set VCPKG_ROOT=${{github.workspace}}\VcPkg\vcpkg
        echo "bootstrap done"
        vcpkg install --triplet x64-windows
        # echo "vcpkg install --triplet x64-windows # done"
        # ${{github.workspace}}\VcPkg\vcpkg\vcpkg.exe install nlopt:x64-windows
        echo "install nlopt done"

    - name: Configure CMake
      run: |
        echo "Set environment variables"
        echo "Configure CMake"
        echo "github.workspace: ${github.workspace} "
        set VCPKG_ROOT="${{github.workspace}}/VcPkg/vcpkg"
        set CMAKE_TOOLCHAIN_FILE="${{VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake" 
        echo "VCPKG_ROOT=${{VCPKG_ROOT}}"
        echo "CMAKE_TOOLCHAIN_FILE=${{CMAKE_TOOLCHAIN_FILE}}"
#        mkdir -p ${{github.workspace}}/build
#        echo "BUILD_DIR=${github.workspace}/build"
#        set VCPKG_DEFAULT_TRIPLET=x64-windows
#        set VCPKG_TRIPLET=x64-windows
#        echo "pwd:"
#        echo "Configuration:"
#        cd       ${{github.workspace}}/build
#        cmake -DCMAKE_TOOLCHAIN_FILE="${{VCMAKE_TOOLCHAIN_FILE}}" -S .. -B ${github.workspace}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
##        cmake -S . -B ${github.workspace}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

##
##    - name: Install nlopt
##      run: |
##        dir C:\vcpkg\scripts\buildsystems\vcpkg.cmake
##        setx CMAKE_TOOLCHAIN_FILE C:\vcpkg\scripts\buildsystems\vcpkg.cmake
##        # set CMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake
##        # set CMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
##        vcpkg install nlopt
#
#
##
##    - name: Configure CMake
##      run: |
##        echo "Configure CMake"
##        CMAKE_TOOLCHAIN_FILE=${{github.workspace}}/VcPkg/vcpkg/scripts/buildsystems/vcpkg.cmake cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
##        echo "Configure CMake completed?"
##    - name: Configure CMake
##      run: |
##        echo "Configure CMake"
##        mkdir -p ${{github.workspace}}/build
##        #
##        cmake -S . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
##        # setx CMAKE_TOOLCHAIN_FILE C:\vcpkg\scripts\buildsystems\vcpkg.cmake
##        # set CMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake
##        # set CMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake
##        echo  "Configure CMake completed?"
